-- =====================================================================================================
-- Migration V11: CEL rule engine (ADR-0025, LLD-18).
--
-- Parameter library (sys object + attributes, addressed in CEL as <object>.<attribute>), CEL rules, rule groups with
-- an evaluation policy, multilingual messages (sys bundle), actions, communication channels (email / push / API),
-- trigger points for integrating applications, and a value-free evaluation log.
--
-- Conventions follow V1: uuid keys generated by the application (UUIDv7), timestamptz in UTC, closed value sets as
-- text + CHECK, mutable rows carry row_version and created_/updated_ columns.
--   * tenant_id / organization_id are opaque ids owned by the host (ADR-0005): no foreign keys.
--     organization_id NULL = the rule/group applies to every organization of the tenant.
--   * The parameter library and the bundles are platform-wide (shared by every tenant); rules, groups, triggers and
--     channel configuration are tenant-owned.
--   * Evaluation input values are NEVER stored (LLD-12 / CLAUDE.md: no row data in logs or tables).
-- =====================================================================================================

-- ---------------------------------------------------------------------------------------------------
-- Change markers: every replica polls one tiny row per scope and reloads its in-memory snapshot when the number
-- moved (same idea as the configuration generations of ADR-0006). No sticky state, no extra infrastructure.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_change_marker
(
    scope      text        NOT NULL,
    version    bigint      NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_change_marker PRIMARY KEY (scope),
    CONSTRAINT ck_re_change_marker_scope CHECK (scope IN ('PARAMETERS', 'BUNDLES', 'RULES'))
);
INSERT INTO dai_re_change_marker (scope) VALUES ('PARAMETERS'), ('BUNDLES'), ('RULES');
COMMENT ON TABLE dai_re_change_marker IS 'Per-scope change counter polled by every node to refresh its rule-engine cache.';

-- Statement-level: one bump per statement however many rows it touches. TG_ARGV[0] names the scope.
CREATE OR REPLACE FUNCTION dai_re_bump_marker() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    UPDATE dai_re_change_marker SET version = version + 1, updated_at = now() WHERE scope = TG_ARGV[0];
    RETURN NULL;
END
$$;

-- ---------------------------------------------------------------------------------------------------
-- Modules the rules are selected by (LOAN, HR, ORDERS ...). Platform-wide list.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_module
(
    id          uuid        NOT NULL DEFAULT gen_random_uuid(),
    code        text        NOT NULL,
    name        text        NOT NULL,
    description text,
    active      boolean     NOT NULL DEFAULT true,
    row_version bigint      NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_module PRIMARY KEY (id),
    CONSTRAINT uq_re_module_code UNIQUE (code),
    CONSTRAINT ck_re_module_code CHECK (code ~ '^[A-Z][A-Z0-9_]{0,63}$')
);
CREATE TRIGGER trg_re_module_touch BEFORE UPDATE ON dai_re_module
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
COMMENT ON TABLE dai_re_module IS 'Business module a rule or rule group belongs to; selected in the UI before rules are listed.';

-- ---------------------------------------------------------------------------------------------------
-- Parameter library: sys object + sys object attribute. "customer" + "age" is the CEL variable customer.age.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_sys_object
(
    id          uuid        NOT NULL DEFAULT gen_random_uuid(),
    code        text        NOT NULL,
    name        text        NOT NULL,
    description text,
    module_id   uuid,
    active      boolean     NOT NULL DEFAULT true,
    row_version bigint      NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_sys_object PRIMARY KEY (id),
    CONSTRAINT uq_re_sys_object_code UNIQUE (code),
    -- a CEL identifier that cannot collide with a CEL keyword or built-in namespace
    CONSTRAINT ck_re_sys_object_code CHECK (code ~ '^[a-z][a-zA-Z0-9_]{0,63}$'
        AND code NOT IN ('true', 'false', 'null', 'in', 'as', 'break', 'const', 'continue', 'else', 'for', 'function',
                         'if', 'import', 'let', 'loop', 'package', 'namespace', 'return', 'var', 'void', 'while')),
    CONSTRAINT fk_re_sys_object_module FOREIGN KEY (module_id) REFERENCES dai_re_module (id)
);
CREATE INDEX ix_re_sys_object_module ON dai_re_sys_object (module_id);
CREATE TRIGGER trg_re_sys_object_touch BEFORE UPDATE ON dai_re_sys_object
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_sys_object_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_sys_object
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('PARAMETERS');
COMMENT ON TABLE dai_re_sys_object IS 'Parameter library root: a named business object (customer, order, loan) exposed to CEL rules.';
COMMENT ON COLUMN dai_re_sys_object.module_id IS 'NULL = shared by every module.';

CREATE TABLE dai_re_sys_object_attribute
(
    id            uuid        NOT NULL DEFAULT gen_random_uuid(),
    object_id     uuid        NOT NULL,
    code          text        NOT NULL,
    name          text        NOT NULL,
    description   text,
    data_type     text        NOT NULL,
    required      boolean     NOT NULL DEFAULT false,
    sample_value  text,
    active        boolean     NOT NULL DEFAULT true,
    row_version   bigint      NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_sys_object_attribute PRIMARY KEY (id),
    CONSTRAINT uq_re_sys_object_attribute UNIQUE (object_id, code),
    CONSTRAINT ck_re_sys_object_attribute_code CHECK (code ~ '^[a-z][a-zA-Z0-9_]{0,63}$'),
    CONSTRAINT ck_re_sys_object_attribute_type CHECK (data_type IN
        ('STRING', 'INT', 'DOUBLE', 'BOOL', 'TIMESTAMP', 'DURATION', 'LIST_STRING', 'LIST_INT', 'LIST_DOUBLE', 'MAP', 'ANY')),
    CONSTRAINT fk_re_sys_object_attribute_object FOREIGN KEY (object_id) REFERENCES dai_re_sys_object (id)
);
CREATE TRIGGER trg_re_sys_object_attribute_touch BEFORE UPDATE ON dai_re_sys_object_attribute
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_sys_object_attribute_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_sys_object_attribute
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('PARAMETERS');
COMMENT ON TABLE dai_re_sys_object_attribute IS 'Parameter library leaf: object.attribute is the typed CEL variable a rule may read.';

-- Read model the cache loads: one row per CEL variable, e.g. cel_name = customer.age.
CREATE VIEW dai_re_parameter_v AS
SELECT a.id            AS attribute_id,
       o.id            AS object_id,
       o.code || '.' || a.code AS cel_name,
       o.code          AS object_code,
       a.code          AS attribute_code,
       a.data_type,
       a.required,
       o.module_id,
       o.name          AS object_name,
       a.name          AS attribute_name,
       a.description
FROM dai_re_sys_object o
         JOIN dai_re_sys_object_attribute a ON a.object_id = o.id
WHERE o.active
  AND a.active;

-- ---------------------------------------------------------------------------------------------------
-- Multilingual messages: a bundle has one text per language.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_sys_bundle
(
    id          uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id   uuid,
    code        text        NOT NULL,
    description text,
    row_version bigint      NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_sys_bundle PRIMARY KEY (id),
    CONSTRAINT uq_re_sys_bundle_code UNIQUE NULLS NOT DISTINCT (tenant_id, code),
    CONSTRAINT ck_re_sys_bundle_code CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')
);
CREATE TRIGGER trg_re_sys_bundle_touch BEFORE UPDATE ON dai_re_sys_bundle
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
COMMENT ON TABLE dai_re_sys_bundle IS 'A message identity; its texts live in dai_re_sys_bundle_message. tenant_id NULL = platform default.';

CREATE TABLE dai_re_sys_bundle_message
(
    bundle_id    uuid        NOT NULL,
    language     text        NOT NULL,
    message_text text        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_sys_bundle_message PRIMARY KEY (bundle_id, language),
    -- BCP 47 language tag, lower-case language + optional region: en, hi, th, pt-BR
    CONSTRAINT ck_re_sys_bundle_message_language CHECK (language ~ '^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$'),
    CONSTRAINT fk_re_sys_bundle_message_bundle FOREIGN KEY (bundle_id) REFERENCES dai_re_sys_bundle (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_re_sys_bundle_message_touch BEFORE UPDATE ON dai_re_sys_bundle_message
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_sys_bundle_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_sys_bundle
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('BUNDLES');
CREATE TRIGGER trg_re_sys_bundle_message_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_sys_bundle_message
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('BUNDLES');
COMMENT ON COLUMN dai_re_sys_bundle_message.message_text IS 'Static text shown to the end user; placeholders are not interpolated.';

-- ---------------------------------------------------------------------------------------------------
-- Rules: one CEL boolean expression + what to say and do when it is true / false.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_rule
(
    id                      uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id               uuid        NOT NULL,
    organization_id         uuid,
    module_id               uuid        NOT NULL,
    code                    text        NOT NULL,
    name                    text        NOT NULL,
    description             text,
    cel_expression          text        NOT NULL,
    status                  text        NOT NULL DEFAULT 'DRAFT',
    -- what to tell and do for each outcome; NULL message = silent for that outcome
    true_message_bundle_id  uuid,
    false_message_bundle_id uuid,
    true_action             text        NOT NULL DEFAULT 'ALLOW',
    false_action            text        NOT NULL DEFAULT 'ALLOW',
    row_version             bigint      NOT NULL DEFAULT 0,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_rule PRIMARY KEY (id),
    CONSTRAINT uq_re_rule_code UNIQUE NULLS NOT DISTINCT (tenant_id, organization_id, module_id, code),
    CONSTRAINT ck_re_rule_code CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
    CONSTRAINT ck_re_rule_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_re_rule_expression CHECK (length(cel_expression) BETWEEN 1 AND 8192),
    CONSTRAINT ck_re_rule_true_action CHECK (true_action IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT ck_re_rule_false_action CHECK (false_action IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT fk_re_rule_module FOREIGN KEY (module_id) REFERENCES dai_re_module (id),
    CONSTRAINT fk_re_rule_true_bundle FOREIGN KEY (true_message_bundle_id) REFERENCES dai_re_sys_bundle (id),
    CONSTRAINT fk_re_rule_false_bundle FOREIGN KEY (false_message_bundle_id) REFERENCES dai_re_sys_bundle (id)
);
CREATE INDEX ix_re_rule_scope ON dai_re_rule (tenant_id, module_id, status);
CREATE TRIGGER trg_re_rule_touch BEFORE UPDATE ON dai_re_rule
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_rule_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_rule
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');
COMMENT ON COLUMN dai_re_rule.cel_expression IS 'CEL boolean expression over library parameters, e.g. customer.age >= 18 && loan.amount <= 500000.';
COMMENT ON COLUMN dai_re_rule.true_action IS 'Action when the expression is true: ALLOW the transaction, WARN, or BLOCK it.';

-- Parameters a rule reads (impact analysis: "which rules break if I change customer.age?"); kept by the admin API
-- from the compiled expression.
CREATE TABLE dai_re_rule_parameter
(
    rule_id      uuid NOT NULL,
    attribute_id uuid NOT NULL,
    CONSTRAINT pk_re_rule_parameter PRIMARY KEY (rule_id, attribute_id),
    CONSTRAINT fk_re_rule_parameter_rule FOREIGN KEY (rule_id) REFERENCES dai_re_rule (id) ON DELETE CASCADE,
    CONSTRAINT fk_re_rule_parameter_attribute FOREIGN KEY (attribute_id) REFERENCES dai_re_sys_object_attribute (id)
);
CREATE INDEX ix_re_rule_parameter_attribute ON dai_re_rule_parameter (attribute_id);

-- ---------------------------------------------------------------------------------------------------
-- Rule groups + evaluation policy
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_rule_group
(
    id                        uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id                 uuid        NOT NULL,
    organization_id           uuid,
    module_id                 uuid        NOT NULL,
    code                      text        NOT NULL,
    name                      text        NOT NULL,
    description               text,
    status                    text        NOT NULL DEFAULT 'DRAFT',
    -- FIRST_MATCH: stop at the first rule (by sequence) whose result equals match_on
    -- ALL_MATCH:   every rule whose result equals match_on
    -- EVALUATE_ALL: every rule, true and false
    -- COMPOSITE:   all rules must be true; one group message for the whole group
    evaluation_policy         text        NOT NULL,
    match_on                  text        NOT NULL DEFAULT 'TRUE',
    -- COMPOSITE only: the group-level message and action when every rule is true / when any rule is false
    composite_true_bundle_id  uuid,
    composite_false_bundle_id uuid,
    composite_true_action     text        NOT NULL DEFAULT 'ALLOW',
    composite_false_action    text        NOT NULL DEFAULT 'BLOCK',
    -- what a rule that cannot be evaluated (missing parameter, type error, timeout) means
    on_error                  text        NOT NULL DEFAULT 'BLOCK',
    row_version               bigint      NOT NULL DEFAULT 0,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_rule_group PRIMARY KEY (id),
    CONSTRAINT uq_re_rule_group_code UNIQUE NULLS NOT DISTINCT (tenant_id, organization_id, module_id, code),
    CONSTRAINT ck_re_rule_group_code CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
    CONSTRAINT ck_re_rule_group_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_re_rule_group_policy CHECK (evaluation_policy IN ('FIRST_MATCH', 'ALL_MATCH', 'EVALUATE_ALL', 'COMPOSITE')),
    CONSTRAINT ck_re_rule_group_match_on CHECK (match_on IN ('TRUE', 'FALSE')),
    CONSTRAINT ck_re_rule_group_true_action CHECK (composite_true_action IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT ck_re_rule_group_false_action CHECK (composite_false_action IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT ck_re_rule_group_on_error CHECK (on_error IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT ck_re_rule_group_composite_msgs CHECK (
        evaluation_policy = 'COMPOSITE' OR (composite_true_bundle_id IS NULL AND composite_false_bundle_id IS NULL)),
    CONSTRAINT fk_re_rule_group_module FOREIGN KEY (module_id) REFERENCES dai_re_module (id),
    CONSTRAINT fk_re_rule_group_true_bundle FOREIGN KEY (composite_true_bundle_id) REFERENCES dai_re_sys_bundle (id),
    CONSTRAINT fk_re_rule_group_false_bundle FOREIGN KEY (composite_false_bundle_id) REFERENCES dai_re_sys_bundle (id)
);
CREATE INDEX ix_re_rule_group_scope ON dai_re_rule_group (tenant_id, module_id, status);
CREATE TRIGGER trg_re_rule_group_touch BEFORE UPDATE ON dai_re_rule_group
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_rule_group_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_rule_group
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');

CREATE TABLE dai_re_rule_group_rule
(
    group_id uuid    NOT NULL,
    rule_id  uuid    NOT NULL,
    sequence integer NOT NULL,
    enabled  boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_re_rule_group_rule PRIMARY KEY (group_id, rule_id),
    CONSTRAINT uq_re_rule_group_rule_sequence UNIQUE (group_id, sequence) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_re_rule_group_rule_sequence CHECK (sequence >= 0),
    CONSTRAINT fk_re_rule_group_rule_group FOREIGN KEY (group_id) REFERENCES dai_re_rule_group (id) ON DELETE CASCADE,
    CONSTRAINT fk_re_rule_group_rule_rule FOREIGN KEY (rule_id) REFERENCES dai_re_rule (id)
);
CREATE INDEX ix_re_rule_group_rule_rule ON dai_re_rule_group_rule (rule_id);
CREATE TRIGGER trg_re_rule_group_rule_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_rule_group_rule
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');

-- ---------------------------------------------------------------------------------------------------
-- Communication: email templates, API endpoints (environment-aware), and the channels bound to an outcome
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_email_template
(
    id           uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id    uuid        NOT NULL,
    -- the id the caller's mail system knows the template by; shown in the UI next to the name
    template_ref text        NOT NULL,
    name         text        NOT NULL,
    description  text,
    active       boolean     NOT NULL DEFAULT true,
    row_version  bigint      NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_email_template PRIMARY KEY (id),
    CONSTRAINT uq_re_email_template_ref UNIQUE (tenant_id, template_ref)
);
CREATE TRIGGER trg_re_email_template_touch BEFORE UPDATE ON dai_re_email_template
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_email_template_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_email_template
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');

CREATE TABLE dai_re_api_endpoint
(
    id                     uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id              uuid        NOT NULL,
    name                   text        NOT NULL,
    http_method            text        NOT NULL DEFAULT 'POST',
    url                    text        NOT NULL,
    -- DEV / QA / PROD endpoints are only callable from the matching environment; EXTERNAL cannot be classified
    environment            text        NOT NULL,
    timeout_ms             integer     NOT NULL DEFAULT 3000,
    -- secrets are never stored here: a reference resolved by the host (e.g. a vault key)
    auth_secret_ref        text,
    -- EXTERNAL endpoints need a recorded human confirmation ("this may be a production API, confirm")
    external_confirmed_by  text,
    external_confirmed_at  timestamptz,
    active                 boolean     NOT NULL DEFAULT true,
    row_version            bigint      NOT NULL DEFAULT 0,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_api_endpoint PRIMARY KEY (id),
    CONSTRAINT uq_re_api_endpoint_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_re_api_endpoint_method CHECK (http_method IN ('POST', 'PUT', 'PATCH', 'GET')),
    CONSTRAINT ck_re_api_endpoint_url CHECK (url ~ '^https?://[^\s]+$'),
    CONSTRAINT ck_re_api_endpoint_environment CHECK (environment IN ('DEV', 'QA', 'PROD', 'EXTERNAL')),
    CONSTRAINT ck_re_api_endpoint_timeout CHECK (timeout_ms BETWEEN 100 AND 30000),
    CONSTRAINT ck_re_api_endpoint_confirmation CHECK (
        environment <> 'EXTERNAL' OR (external_confirmed_by IS NOT NULL AND external_confirmed_at IS NOT NULL))
);
CREATE TRIGGER trg_re_api_endpoint_touch BEFORE UPDATE ON dai_re_api_endpoint
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_api_endpoint_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_api_endpoint
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');
COMMENT ON COLUMN dai_re_api_endpoint.environment IS 'DEV/QA/PROD must match the running environment; EXTERNAL requires external_confirmed_*.';

-- An outcome channel: when <owner> produces <on_result>, communicate through <channel_type>.
CREATE TABLE dai_re_outcome_channel
(
    id                  uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id           uuid        NOT NULL,
    owner_type          text        NOT NULL,
    owner_id            uuid        NOT NULL,
    on_result           text        NOT NULL,
    channel_type        text        NOT NULL,
    sequence            integer     NOT NULL DEFAULT 0,
    enabled             boolean     NOT NULL DEFAULT true,
    email_template_id   uuid,
    api_endpoint_id     uuid,
    push_title_bundle_id uuid,
    push_body_bundle_id uuid,
    -- CEL expression yielding the recipient (email address, device/user id) from the evaluation facts
    recipient_expression text,
    row_version         bigint      NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_outcome_channel PRIMARY KEY (id),
    CONSTRAINT ck_re_outcome_channel_owner CHECK (owner_type IN ('RULE', 'GROUP')),
    CONSTRAINT ck_re_outcome_channel_result CHECK (on_result IN ('TRUE', 'FALSE', 'ERROR', 'ANY')),
    CONSTRAINT ck_re_outcome_channel_type CHECK (channel_type IN ('EMAIL', 'PUSH', 'API')),
    CONSTRAINT ck_re_outcome_channel_shape CHECK (
        (channel_type = 'EMAIL' AND email_template_id IS NOT NULL AND api_endpoint_id IS NULL AND push_body_bundle_id IS NULL)
        OR (channel_type = 'API' AND api_endpoint_id IS NOT NULL AND email_template_id IS NULL AND push_body_bundle_id IS NULL)
        OR (channel_type = 'PUSH' AND push_body_bundle_id IS NOT NULL AND email_template_id IS NULL AND api_endpoint_id IS NULL)),
    CONSTRAINT fk_re_outcome_channel_template FOREIGN KEY (email_template_id) REFERENCES dai_re_email_template (id),
    CONSTRAINT fk_re_outcome_channel_endpoint FOREIGN KEY (api_endpoint_id) REFERENCES dai_re_api_endpoint (id),
    CONSTRAINT fk_re_outcome_channel_push_title FOREIGN KEY (push_title_bundle_id) REFERENCES dai_re_sys_bundle (id),
    CONSTRAINT fk_re_outcome_channel_push_body FOREIGN KEY (push_body_bundle_id) REFERENCES dai_re_sys_bundle (id)
);
CREATE INDEX ix_re_outcome_channel_owner ON dai_re_outcome_channel (owner_type, owner_id);
CREATE TRIGGER trg_re_outcome_channel_touch BEFORE UPDATE ON dai_re_outcome_channel
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_outcome_channel_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_outcome_channel
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');
COMMENT ON TABLE dai_re_outcome_channel IS 'Communication bound to a rule or group outcome. owner_id is polymorphic (rule or group), checked by the admin API.';

-- ---------------------------------------------------------------------------------------------------
-- Trigger points: how an application in the host's environment reaches a rule group
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_trigger_point
(
    id              uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id       uuid        NOT NULL,
    organization_id uuid,
    application     text        NOT NULL,
    module_id       uuid        NOT NULL,
    trigger_type    text        NOT NULL,
    form_code       text        NOT NULL,
    -- SUBMIT, APPROVE, ADD, BUY ... (free: owned by the integrating application)
    action_code     text        NOT NULL,
    -- set for FORM_FIELD triggers (ON_CHANGE of one field)
    field_code      text,
    rule_group_id   uuid        NOT NULL,
    sequence        integer     NOT NULL DEFAULT 0,
    enabled         boolean     NOT NULL DEFAULT true,
    row_version     bigint      NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_trigger_point PRIMARY KEY (id),
    CONSTRAINT uq_re_trigger_point UNIQUE NULLS NOT DISTINCT
        (tenant_id, organization_id, application, trigger_type, form_code, action_code, field_code, rule_group_id),
    CONSTRAINT ck_re_trigger_point_type CHECK (trigger_type IN ('FORM_ACTION', 'FORM_FIELD')),
    CONSTRAINT ck_re_trigger_point_field CHECK (
        (trigger_type = 'FORM_FIELD') = (field_code IS NOT NULL)),
    CONSTRAINT ck_re_trigger_point_codes CHECK (
        application ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$' AND form_code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
        AND action_code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
    CONSTRAINT fk_re_trigger_point_module FOREIGN KEY (module_id) REFERENCES dai_re_module (id),
    CONSTRAINT fk_re_trigger_point_group FOREIGN KEY (rule_group_id) REFERENCES dai_re_rule_group (id)
);
CREATE INDEX ix_re_trigger_point_lookup ON dai_re_trigger_point (tenant_id, application, form_code, action_code);
CREATE TRIGGER trg_re_trigger_point_touch BEFORE UPDATE ON dai_re_trigger_point
    FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
CREATE TRIGGER trg_re_trigger_point_marker AFTER INSERT OR UPDATE OR DELETE ON dai_re_trigger_point
    FOR EACH STATEMENT EXECUTE FUNCTION dai_re_bump_marker('RULES');
COMMENT ON TABLE dai_re_trigger_point IS 'Binds (application, form, action[, field]) to a rule group; many groups per trigger run in sequence order.';

-- ---------------------------------------------------------------------------------------------------
-- Evaluation log: what was decided, never the input values
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_re_evaluation
(
    id              uuid        NOT NULL DEFAULT gen_random_uuid(),
    tenant_id       uuid        NOT NULL,
    organization_id uuid,
    rule_group_id   uuid        NOT NULL,
    trigger_point_id uuid,
    policy          text        NOT NULL,
    decision        text        NOT NULL,
    language        text,
    duration_micros bigint      NOT NULL DEFAULT 0,
    evaluated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_re_evaluation PRIMARY KEY (id),
    CONSTRAINT ck_re_evaluation_decision CHECK (decision IN ('ALLOW', 'WARN', 'BLOCK'))
);
CREATE INDEX ix_re_evaluation_group ON dai_re_evaluation (tenant_id, rule_group_id, evaluated_at DESC);
COMMENT ON TABLE dai_re_evaluation IS 'One row per group evaluation. No input values are stored. Purged by retention (LLD-15 §retention).';

CREATE TABLE dai_re_evaluation_result
(
    evaluation_id uuid    NOT NULL,
    rule_id       uuid    NOT NULL,
    sequence      integer NOT NULL,
    outcome       text    NOT NULL,
    action        text    NOT NULL,
    error_code    text,
    CONSTRAINT pk_re_evaluation_result PRIMARY KEY (evaluation_id, rule_id),
    CONSTRAINT ck_re_evaluation_result_outcome CHECK (outcome IN ('TRUE', 'FALSE', 'ERROR')),
    CONSTRAINT ck_re_evaluation_result_action CHECK (action IN ('ALLOW', 'WARN', 'BLOCK')),
    CONSTRAINT fk_re_evaluation_result_evaluation FOREIGN KEY (evaluation_id) REFERENCES dai_re_evaluation (id) ON DELETE CASCADE
);
