-- =====================================================================================================
-- springAIMcpServerCommon — PostgreSQL store, migration V1: foundation, identity references, access
-- Schema: dynamic_ai (Flyway sets search_path to it; objects are created unqualified).
-- Design: docs/lld/15-database-schema.md, ADR-0019. Minimum PostgreSQL 15 (UNIQUE NULLS NOT DISTINCT).
--
-- Conventions
--   * Primary keys: uuid generated by the application (UUIDv7, time-ordered); gen_random_uuid() only as fallback.
--   * Timestamps: timestamptz, always UTC from the application.
--   * Closed value sets: text + CHECK constraint (easy to extend in a later migration; no enum types).
--   * Mutable configuration rows carry row_version (JPA optimistic locking) and created_/updated_ columns.
--   * We never store passwords, e-mail addresses or tokens. Identity is owned by the host's IdP (ADR-0005);
--     dai_principal only references external subjects so that other tables can use a compact foreign key.
-- =====================================================================================================

-- ---------------------------------------------------------------------------------------------------
-- Shared functions
-- ---------------------------------------------------------------------------------------------------

-- Keeps updated_at correct even for writes that bypass JPA (manual fixes, scripts).
CREATE OR REPLACE FUNCTION dai_touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END
$$;

-- Guards append-only tables (audit, evidence). Retention removes whole partitions with DROP TABLE,
-- which does not fire row triggers, so no bypass switch is needed.
CREATE OR REPLACE FUNCTION dai_forbid_modification() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'table %.% is append-only (% not allowed)', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END
$$;

-- Creates monthly range partitions (UTC month boundaries) named <table>_pYYYYMM for a partitioned parent.
-- Idempotent. Called by migrations and by the library's partition-maintenance job (LLD-15 §6).
-- If the DEFAULT partition already holds rows for a month, creating that month fails with check_violation;
-- the month is then skipped with a WARNING (the maintenance job reports it) instead of aborting the rest.
CREATE OR REPLACE FUNCTION dai_ensure_monthly_partitions(p_parent regclass,
                                                         p_months_back integer DEFAULT 1,
                                                         p_months_ahead integer DEFAULT 3) RETURNS integer
    LANGUAGE plpgsql AS
$$
DECLARE
    v_schema  text;
    v_table   text;
    v_start   date;
    v_name    text;
    v_created integer := 0;
    i         integer;
BEGIN
    SELECT n.nspname, c.relname
      INTO v_schema, v_table
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE c.oid = p_parent;

    FOR i IN -p_months_back .. p_months_ahead
        LOOP
            v_start := (date_trunc('month', now() AT TIME ZONE 'UTC') + make_interval(months => i))::date;
            v_name := format('%s_p%s', v_table, to_char(v_start, 'YYYYMM'));
            IF to_regclass(format('%I.%I', v_schema, v_name)) IS NULL THEN
                BEGIN
                    EXECUTE format('CREATE TABLE %I.%I PARTITION OF %I.%I FOR VALUES FROM (%L) TO (%L)',
                                   v_schema, v_name, v_schema, v_table,
                                   to_char(v_start, 'YYYY-MM-DD') || ' 00:00:00+00',
                                   to_char((v_start + interval '1 month')::date, 'YYYY-MM-DD') || ' 00:00:00+00');
                    v_created := v_created + 1;
                EXCEPTION
                    WHEN check_violation THEN
                        RAISE WARNING 'partition % not created: default partition of % holds rows for that month',
                            v_name, v_table;
                END;
            END IF;
        END LOOP;
    RETURN v_created;
END
$$;

-- Drops monthly partitions whose whole range ends at or before p_before (retention).
-- Evidence partitions containing rows under an active legal hold are kept.
CREATE OR REPLACE FUNCTION dai_drop_monthly_partitions_before(p_parent regclass, p_before timestamptz) RETURNS integer
    LANGUAGE plpgsql AS
$$
DECLARE
    v_child   record;
    v_end     timestamptz;
    v_held    boolean;
    v_dropped integer := 0;
BEGIN
    FOR v_child IN
        SELECT n.nspname AS schema_name, c.relname AS table_name
          FROM pg_inherits i
          JOIN pg_class c ON c.oid = i.inhrelid
          JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE i.inhparent = p_parent
           AND c.relname ~ '_p[0-9]{6}$'
        LOOP
            v_end := (to_date(right(v_child.table_name, 6), 'YYYYMM') + interval '1 month')::timestamp AT TIME ZONE 'UTC';
            CONTINUE WHEN v_end > p_before;

            IF v_child.table_name LIKE 'dai_audit_evidence_p%' THEN
                EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I.%I e JOIN dai_evidence_legal_hold h '
                               || 'ON h.subject_key_id = e.subject_key_id AND h.released_at IS NULL)',
                               v_child.schema_name, v_child.table_name) INTO v_held;
                CONTINUE WHEN v_held;
            END IF;

            EXECUTE format('ALTER TABLE %s DETACH PARTITION %I.%I', p_parent, v_child.schema_name, v_child.table_name);
            EXECUTE format('DROP TABLE %I.%I', v_child.schema_name, v_child.table_name);
            v_dropped := v_dropped + 1;
        END LOOP;
    RETURN v_dropped;
END
$$;

-- ---------------------------------------------------------------------------------------------------
-- Environment identity of this store (LLD-12 §3: a stage app must never load a prod config store)
-- Exactly one row, written by the application on first start.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_environment
(
    singleton      boolean     NOT NULL DEFAULT true,
    environment_id text        NOT NULL,
    tier           text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_environment PRIMARY KEY (singleton),
    CONSTRAINT ck_environment_singleton CHECK (singleton),
    CONSTRAINT ck_environment_tier CHECK (tier IN ('DEV', 'TEST', 'STAGE', 'PROD')),
    CONSTRAINT ck_environment_id CHECK (environment_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')
);
COMMENT ON TABLE dai_environment IS 'Single-row identity of the environment that owns this store (LLD-12 §3).';

-- ---------------------------------------------------------------------------------------------------
-- Principals: references to subjects owned by the host IdP (users, groups), our service accounts and MCP clients
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_principal
(
    id            uuid        NOT NULL DEFAULT gen_random_uuid(),
    subject_type  text        NOT NULL,
    issuer        text        NOT NULL,
    external_id   text        NOT NULL,
    display_name  text,
    status        text        NOT NULL DEFAULT 'ACTIVE',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_principal PRIMARY KEY (id),
    CONSTRAINT uq_principal_subject UNIQUE (issuer, subject_type, external_id),
    CONSTRAINT ck_principal_subject_type CHECK (subject_type IN ('USER', 'GROUP', 'SERVICE_ACCOUNT', 'MCP_CLIENT')),
    CONSTRAINT ck_principal_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_principal_issuer_len CHECK (length(issuer) BETWEEN 1 AND 512),
    CONSTRAINT ck_principal_external_id_len CHECK (length(external_id) BETWEEN 1 AND 512)
);
COMMENT ON TABLE dai_principal IS 'External subject reference (IdP sub/oid, LDAP DN, group id, service account, MCP client). Never deleted, only disabled, so audit rows stay resolvable.';
COMMENT ON COLUMN dai_principal.issuer IS 'OIDC issuer URI, ldap:<base DN>, saml:<entity id>, or dai for framework service accounts.';

-- ---------------------------------------------------------------------------------------------------
-- Workspaces (teams) and membership
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_workspace
(
    id                       uuid        NOT NULL DEFAULT gen_random_uuid(),
    slug                     text        NOT NULL,
    name                     text        NOT NULL,
    description              text,
    tenant_id                text,
    classification_clearance text        NOT NULL DEFAULT 'INTERNAL',
    status                   text        NOT NULL DEFAULT 'ACTIVE',
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid,
    updated_at               timestamptz NOT NULL DEFAULT now(),
    updated_by               uuid,
    row_version              bigint      NOT NULL DEFAULT 0,
    CONSTRAINT pk_workspace PRIMARY KEY (id),
    CONSTRAINT uq_workspace_slug UNIQUE (slug),
    CONSTRAINT ck_workspace_slug CHECK (slug ~ '^[a-z][a-z0-9-]{1,62}$'),
    CONSTRAINT ck_workspace_clearance CHECK (classification_clearance IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    CONSTRAINT ck_workspace_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT fk_workspace_created_by FOREIGN KEY (created_by) REFERENCES dai_principal (id),
    CONSTRAINT fk_workspace_updated_by FOREIGN KEY (updated_by) REFERENCES dai_principal (id)
);
CREATE INDEX ix_workspace_tenant ON dai_workspace (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE TRIGGER trg_workspace_touch BEFORE UPDATE ON dai_workspace FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();
COMMENT ON TABLE dai_workspace IS 'Team boundary that owns resources, grants, budgets (F-62). Archived, never deleted.';

CREATE TABLE dai_workspace_member
(
    workspace_id uuid        NOT NULL,
    principal_id uuid        NOT NULL,
    role         text        NOT NULL,
    granted_by   uuid,
    granted_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz,
    CONSTRAINT pk_workspace_member PRIMARY KEY (workspace_id, principal_id, role),
    CONSTRAINT ck_workspace_member_role CHECK (role IN ('WORKSPACE_OWNER', 'AUTHOR', 'APPROVER', 'OPERATOR', 'AUDITOR', 'CONSUMER')),
    CONSTRAINT ck_workspace_member_expiry CHECK (expires_at IS NULL OR expires_at > granted_at),
    CONSTRAINT fk_workspace_member_workspace FOREIGN KEY (workspace_id) REFERENCES dai_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_workspace_member_principal FOREIGN KEY (principal_id) REFERENCES dai_principal (id),
    CONSTRAINT fk_workspace_member_granted_by FOREIGN KEY (granted_by) REFERENCES dai_principal (id)
);
CREATE INDEX ix_workspace_member_principal ON dai_workspace_member (principal_id);
COMMENT ON TABLE dai_workspace_member IS 'Direct membership (principal may be a GROUP, so IdP group membership drives access).';

-- ---------------------------------------------------------------------------------------------------
-- IdP claim/authority/group → framework role mapping (SEC-01 §3). Bootstrap rules may also come from config.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_role_mapping
(
    id             uuid        NOT NULL DEFAULT gen_random_uuid(),
    source         text        NOT NULL,
    issuer         text,
    claim_name     text,
    match_value    text        NOT NULL,
    framework_role text        NOT NULL,
    workspace_id   uuid,
    priority       integer     NOT NULL DEFAULT 100,
    enabled        boolean     NOT NULL DEFAULT true,
    description    text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     uuid,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     uuid,
    row_version    bigint      NOT NULL DEFAULT 0,
    CONSTRAINT pk_role_mapping PRIMARY KEY (id),
    CONSTRAINT uq_role_mapping UNIQUE NULLS NOT DISTINCT (source, issuer, claim_name, match_value, framework_role, workspace_id),
    CONSTRAINT ck_role_mapping_source CHECK (source IN ('AUTHORITY', 'OIDC_CLAIM', 'LDAP_GROUP', 'SCOPE')),
    CONSTRAINT ck_role_mapping_claim CHECK ((source = 'OIDC_CLAIM') = (claim_name IS NOT NULL)),
    CONSTRAINT ck_role_mapping_role CHECK (framework_role IN ('PLATFORM_ADMIN', 'SECURITY_ADMIN', 'AUDITOR', 'WORKSPACE_OWNER',
                                                              'AUTHOR', 'APPROVER', 'OPERATOR', 'CONSUMER')),
    -- global roles must not be scoped to a workspace; workspace roles must be
    CONSTRAINT ck_role_mapping_scope CHECK (
        (framework_role IN ('PLATFORM_ADMIN', 'SECURITY_ADMIN') AND workspace_id IS NULL)
            OR (framework_role = 'AUDITOR')
            OR (framework_role NOT IN ('PLATFORM_ADMIN', 'SECURITY_ADMIN', 'AUDITOR') AND workspace_id IS NOT NULL)),
    CONSTRAINT fk_role_mapping_workspace FOREIGN KEY (workspace_id) REFERENCES dai_workspace (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_mapping_created_by FOREIGN KEY (created_by) REFERENCES dai_principal (id),
    CONSTRAINT fk_role_mapping_updated_by FOREIGN KEY (updated_by) REFERENCES dai_principal (id)
);
CREATE INDEX ix_role_mapping_lookup ON dai_role_mapping (source, match_value) WHERE enabled;
CREATE TRIGGER trg_role_mapping_touch BEFORE UPDATE ON dai_role_mapping FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();

-- ---------------------------------------------------------------------------------------------------
-- Service accounts and API keys (SEC-01 §9) — the only credentials the framework owns. Secrets are hashed.
-- ---------------------------------------------------------------------------------------------------
CREATE TABLE dai_service_account
(
    id           uuid        NOT NULL DEFAULT gen_random_uuid(),
    principal_id uuid        NOT NULL,
    workspace_id uuid        NOT NULL,
    name         text        NOT NULL,
    description  text,
    status       text        NOT NULL DEFAULT 'ACTIVE',
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   uuid,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   uuid,
    row_version  bigint      NOT NULL DEFAULT 0,
    CONSTRAINT pk_service_account PRIMARY KEY (id),
    CONSTRAINT uq_service_account_principal UNIQUE (principal_id),
    CONSTRAINT uq_service_account_name UNIQUE (workspace_id, name),
    CONSTRAINT ck_service_account_name CHECK (name ~ '^[a-z][a-z0-9-]{1,62}$'),
    CONSTRAINT ck_service_account_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT fk_service_account_principal FOREIGN KEY (principal_id) REFERENCES dai_principal (id),
    CONSTRAINT fk_service_account_workspace FOREIGN KEY (workspace_id) REFERENCES dai_workspace (id),
    CONSTRAINT fk_service_account_created_by FOREIGN KEY (created_by) REFERENCES dai_principal (id),
    CONSTRAINT fk_service_account_updated_by FOREIGN KEY (updated_by) REFERENCES dai_principal (id)
);
CREATE TRIGGER trg_service_account_touch BEFORE UPDATE ON dai_service_account FOR EACH ROW EXECUTE FUNCTION dai_touch_updated_at();

CREATE TABLE dai_api_key
(
    id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
    service_account_id uuid        NOT NULL,
    key_prefix         text        NOT NULL,
    key_hash           text        NOT NULL,
    hash_algorithm     text        NOT NULL DEFAULT 'hmac-sha256',
    expires_at         timestamptz NOT NULL,
    last_used_at       timestamptz,
    revoked_at         timestamptz,
    revoked_by         uuid,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         uuid,
    CONSTRAINT pk_api_key PRIMARY KEY (id),
    CONSTRAINT uq_api_key_prefix UNIQUE (key_prefix),
    CONSTRAINT ck_api_key_prefix CHECK (key_prefix ~ '^dai_[a-z]+_[A-Za-z0-9]{8,32}$'),
    CONSTRAINT ck_api_key_hash_algorithm CHECK (hash_algorithm IN ('hmac-sha256', 'argon2id', 'bcrypt', 'pbkdf2-sha256')),
    CONSTRAINT ck_api_key_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_api_key_revocation CHECK ((revoked_at IS NULL) = (revoked_by IS NULL)),
    CONSTRAINT fk_api_key_service_account FOREIGN KEY (service_account_id) REFERENCES dai_service_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_api_key_revoked_by FOREIGN KEY (revoked_by) REFERENCES dai_principal (id),
    CONSTRAINT fk_api_key_created_by FOREIGN KEY (created_by) REFERENCES dai_principal (id)
);
CREATE INDEX ix_api_key_service_account ON dai_api_key (service_account_id);
CREATE INDEX ix_api_key_active_expiry ON dai_api_key (expires_at) WHERE revoked_at IS NULL;
COMMENT ON COLUMN dai_api_key.key_prefix IS 'Public, unique lookup part of the key (dai_<env>_<keyId>); the secret part is only stored as key_hash.';
COMMENT ON COLUMN dai_api_key.hash_algorithm IS 'hmac-sha256 (server pepper from the host secret store) is the default: keys are 256-bit random secrets, so a slow password hash adds latency without security benefit.';

CREATE TABLE dai_api_key_scope
(
    api_key_id uuid NOT NULL,
    permission text NOT NULL,
    CONSTRAINT pk_api_key_scope PRIMARY KEY (api_key_id, permission),
    CONSTRAINT ck_api_key_scope_permission CHECK (permission ~ '^[a-z][a-z-]*:[a-z][a-z-]*$'),
    CONSTRAINT fk_api_key_scope_key FOREIGN KEY (api_key_id) REFERENCES dai_api_key (id) ON DELETE CASCADE
);

CREATE TABLE dai_api_key_allowed_network
(
    api_key_id uuid NOT NULL,
    network    cidr NOT NULL,
    CONSTRAINT pk_api_key_allowed_network PRIMARY KEY (api_key_id, network),
    CONSTRAINT fk_api_key_allowed_network_key FOREIGN KEY (api_key_id) REFERENCES dai_api_key (id) ON DELETE CASCADE
);
COMMENT ON TABLE dai_api_key_allowed_network IS 'Optional IP allow-list per key; no rows = any network.';
