package com.springaimcpservercommon.loadtest.k6;

import com.springaimcpservercommon.loadtest.data.DataPlan;
import com.springaimcpservercommon.loadtest.data.FieldKeys;
import com.springaimcpservercommon.loadtest.data.FieldKindClassifier;
import com.springaimcpservercommon.loadtest.data.FieldPlan;
import com.springaimcpservercommon.loadtest.discovery.Documents;
import com.springaimcpservercommon.loadtest.model.ApiCatalog;
import com.springaimcpservercommon.loadtest.model.ApiEndpoint;
import com.springaimcpservercommon.loadtest.model.ApiParam;
import com.springaimcpservercommon.loadtest.model.ArraySchema;
import com.springaimcpservercommon.loadtest.model.Constraints;
import com.springaimcpservercommon.loadtest.model.Names;
import com.springaimcpservercommon.loadtest.model.ObjectSchema;
import com.springaimcpservercommon.loadtest.model.ParamLocation;
import com.springaimcpservercommon.loadtest.model.Property;
import com.springaimcpservercommon.loadtest.model.RefSchema;
import com.springaimcpservercommon.loadtest.model.ScalarSchema;
import com.springaimcpservercommon.loadtest.model.Schema;
import tools.jackson.databind.node.ObjectNode;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Writes the generated JavaScript: one request builder per API ({@code apis/<id>.js}), one data provider per
 * named request schema ({@code providers/schemas.js}) and the entry point ({@code main.js}). Every scalar field
 * becomes a {@code field(ctx, spec)} call carrying its key, kind, constraints and real-data pool, so the files
 * read as documentation of the payload and can be edited by hand (they are regenerated, so lasting changes
 * belong in {@code hooks.js} or {@code data/user.json}).
 */
final class JsEmitter {

    static final String GENERATED = "// GENERATED by spring-ai-mcp-server-common-loadtest — regenerate instead of "
            + "editing; lasting changes go in hooks.js, data/user.json or loadtest.config.json.";

    private final ApiCatalog catalog;
    private final DataPlan plan;

    JsEmitter(ApiCatalog catalog, DataPlan plan) {
        this.catalog = catalog;
        this.plan = plan;
    }

    /**
     * JS function name of a named schema provider.
     *
     * @param schemaName schema name
     * @return identifier
     */
    static String provider(String schemaName) {
        String id = Names.jsIdentifier(schemaName);
        return Character.toUpperCase(id.charAt(0)) + id.substring(1);
    }

    String apiModule(ApiEndpoint e) {
        StringBuilder js = new StringBuilder();
        js.append(GENERATED).append('\n');
        js.append("// ").append(e.method()).append(' ').append(e.path());
        if (e.summary() != null) {
            js.append(" — ").append(e.summary().replace('\n', ' '));
        }
        js.append("\n// discovered from: ").append(String.join(", ", new LinkedHashSet<>(e.sources()))).append("\n");
        js.append("import { field, obj, arr, nested, free } from '../lib/data.js';\n");
        boolean usesSchemas = e.body() != null || e.params().stream().anyMatch(p -> p.schema() instanceof RefSchema);
        if (usesSchemas) {
            js.append("import * as S from '../providers/schemas.js';\n");
        }
        ObjectNode meta = Documents.json().createObjectNode();
        meta.put("id", e.id());
        meta.put("method", e.method().name());
        meta.put("path", e.path());
        if (e.bodyType() != null) {
            meta.put("bodyType", e.bodyType()); // form | multipart (default: JSON)
        }
        if (e.isGraphQl()) {
            meta.put("graphql", true); // a 200 with "errors" is a failure
            meta.put("safe", e.tags().contains("graphql:query")); // queries change nothing: allowed when READ_ONLY
        }
        if (e.summary() != null) {
            meta.put("summary", e.summary());
        }
        js.append("\nexport const API = ").append(json(meta)).append(";\n\n");
        js.append("export function build(ctx) {\n  return {\n");
        js.append("    path: {");
        List<ApiParam> path = e.params(ParamLocation.PATH);
        if (!path.isEmpty()) {
            js.append('\n');
            for (ApiParam p : path) {
                js.append("      ").append(json(p.name())).append(": ")
                        .append(expr(p.schema(), FieldKeys.param(e.id(), p.in(), p.name()), p.name(), 6, "S."))
                        .append(",\n");
            }
            js.append("    ");
        }
        js.append("},\n");
        js.append("    query: ").append(params(e, ParamLocation.QUERY)).append(",\n");
        js.append("    headers: ").append(params(e, ParamLocation.HEADER)).append(",\n");
        if (e.body() != null) {
            js.append("    body: ").append(expr(e.body(), FieldKeys.body(e.id()), "body", 4, "S.")).append(",\n");
        }
        js.append("  };\n}\n");
        return js.toString();
    }

    private String params(ApiEndpoint e, ParamLocation location) {
        List<ApiParam> list = e.params(location);
        if (list.isEmpty()) {
            return "{}";
        }
        StringBuilder js = new StringBuilder("obj(ctx, [\n");
        for (ApiParam p : list) {
            js.append("      [").append(json(p.name())).append(", ").append(p.required()).append(", () => ")
                    .append(expr(p.schema(), FieldKeys.param(e.id(), location, p.name()), p.name(), 6, "S."))
                    .append("],\n");
        }
        return js.append("    ])").toString();
    }

    String schemasModule() {
        StringBuilder js = new StringBuilder();
        js.append(GENERATED).append('\n');
        js.append("// One data provider per request schema (DTO) of the project; shared by every API that uses it.\n");
        js.append("import { field, obj, arr, nested, free } from '../lib/data.js';\n");
        Map<String, Set<String>> usedBy = usage();
        Set<String> reachable = reachableSchemas();
        for (Map.Entry<String, ObjectSchema> s : catalog.schemas().entrySet()) {
            if (!reachable.contains(s.getKey())) {
                continue; // e.g. query objects, already flattened into query parameters
            }
            js.append("\n/** ").append(s.getKey());
            Set<String> users = usedBy.getOrDefault(s.getKey(), Set.of());
            if (!users.isEmpty()) {
                js.append(" — used by ").append(String.join(", ", users));
            }
            js.append(" */\n");
            js.append("export function ").append(provider(s.getKey())).append("(ctx) {\n  return ")
                    .append(expr(s.getValue(), s.getKey(), s.getKey(), 2, "")).append(";\n}\n");
        }
        if (reachable.isEmpty()) {
            js.append("\nexport const NONE = true;\n");
        }
        return js.toString();
    }

    /** Named schemas a request can contain: referenced from a body or parameter, transitively. */
    private Set<String> reachableSchemas() {
        Set<String> out = new LinkedHashSet<>();
        for (ApiEndpoint e : catalog.endpoints()) {
            if (e.body() != null) {
                collect(e.body(), out);
            }
            e.params().forEach(p -> collect(p.schema(), out));
        }
        return out;
    }

    private void collect(Schema schema, Set<String> out) {
        switch (schema) {
            case RefSchema(String ref) -> {
                if (out.add(ref) && catalog.schemas().containsKey(ref)) {
                    collect(catalog.schemas().get(ref), out);
                }
            }
            case ArraySchema a -> collect(a.items(), out);
            case ObjectSchema o -> o.properties().values().forEach(p -> collect(p.schema(), out));
            case ScalarSchema s -> { }
        }
    }

    private Map<String, Set<String>> usage() {
        Map<String, Set<String>> out = new LinkedHashMap<>();
        for (ApiEndpoint e : catalog.endpoints()) {
            if (e.body() instanceof RefSchema(String name)) {
                out.computeIfAbsent(name, k -> new LinkedHashSet<>()).add(e.id());
            }
        }
        return out;
    }

    private String expr(Schema schema, String key, String name, int indent, String schemaPrefix) {
        String pad = " ".repeat(indent);
        return switch (schema) {
            case ScalarSchema s -> "field(ctx, " + json(spec(s, key, name)) + ")";
            case ArraySchema a -> {
                ObjectNode bounds = Documents.json().createObjectNode();
                if (a.minItems() != null) {
                    bounds.put("minItems", a.minItems());
                }
                if (a.maxItems() != null) {
                    bounds.put("maxItems", a.maxItems());
                }
                yield "arr(ctx, " + json(bounds) + ", () => " + expr(a.items(), key, name, indent, schemaPrefix) + ")";
            }
            case ObjectSchema o when o.freeForm() || o.properties().isEmpty() -> "free(ctx)";
            case ObjectSchema o -> {
                StringBuilder js = new StringBuilder("obj(ctx, [\n");
                for (Map.Entry<String, Property> p : o.properties().entrySet()) {
                    js.append(pad).append("  [").append(json(p.getKey())).append(", ").append(p.getValue().required())
                            .append(", () => ")
                            .append(expr(p.getValue().schema(), FieldKeys.child(key, p.getKey()), p.getKey(),
                                    indent + 2, schemaPrefix))
                            .append("],\n");
                }
                yield js.append(pad).append("])").toString();
            }
            case RefSchema(String ref) -> catalog.schemas().containsKey(ref)
                    ? "nested(ctx, () => " + schemaPrefix + provider(ref) + "(ctx))"
                    : "free(ctx)";
        };
    }

    private ObjectNode spec(ScalarSchema s, String key, String name) {
        FieldPlan f = plan.field(key);
        ObjectNode spec = Documents.json().createObjectNode();
        spec.put("key", key);
        spec.put("name", name);
        spec.put("owner", f != null ? f.owner() : key.substring(0, key.indexOf('.') < 0 ? key.length() : key.indexOf('.')));
        spec.put("kind", (f != null ? f.kind() : FieldKindClassifier.classify(name, s)).generator());
        ObjectNode schema = schemaNode(s);
        if (f != null && f.maxLength() != null && s.type() == com.springaimcpservercommon.loadtest.model.ScalarType.STRING
                && (!schema.has("maxLength") || schema.path("maxLength").asLong() > f.maxLength())) {
            schema.put("maxLength", f.maxLength()); // the column's length: longer values would fail on insert
        }
        if (f != null && f.unique()) {
            schema.put("unique", true);
        }
        spec.set("schema", schema);
        if (f != null && f.pool() != null) {
            spec.put("real", f.pool().key());
            if (f.component() >= 0) {
                spec.put("component", f.component()); // one tuple (parent row) per request for the whole key
            }
        }
        return spec;
    }

    static ObjectNode schemaNode(ScalarSchema s) {
        ObjectNode n = Documents.json().createObjectNode();
        n.put("type", s.type().name().toLowerCase(Locale.ROOT));
        if (s.format() != null) {
            n.put("format", s.format());
        }
        if (!s.enumValues().isEmpty()) {
            var arr = n.putArray("enum");
            s.enumValues().forEach(arr::add);
        }
        Constraints c = s.constraints();
        if (c.minLength() != null) {
            n.put("minLength", c.minLength());
        }
        if (c.maxLength() != null) {
            n.put("maxLength", c.maxLength());
        }
        if (c.minimum() != null) {
            n.put("minimum", c.minimum());
        }
        if (c.maximum() != null) {
            n.put("maximum", c.maximum());
        }
        if (c.pattern() != null) {
            n.put("pattern", c.pattern());
        }
        if (c.temporal() != null) {
            n.put("temporal", c.temporal().name());
        }
        if (s.example() != null) {
            n.put("example", s.example());
        }
        return n;
    }

    String mainModule(List<ApiEndpoint> endpoints) {
        StringBuilder imports = new StringBuilder();
        StringBuilder list = new StringBuilder();
        StringBuilder execs = new StringBuilder();
        for (ApiEndpoint e : endpoints) {
            String alias = "a_" + e.id();
            imports.append("import * as ").append(alias).append(" from './apis/").append(e.id()).append(".js';\n");
            list.append("  ").append(alias).append(",\n");
            execs.append("export function api_").append(e.id()).append("(auth) {\n  call(RUNTIME.byId[")
                    .append(json(e.id())).append("], RUNTIME, auth, hooks);\n}\n\n");
        }
        return GENERATED + "\n" + """
                //
                // Entry point. Run with:  k6 run -e MODE=<mode> [-e DATA_MODE=<data mode>] [-e API=<id,…>] main.js
                // Modes: %s
                // Data modes: auto | dummy | random | real | user | mixed      (see README.md)
                import { SharedArray } from 'k6/data';
                import * as data from './lib/data.js';
                import { buildOptions, parseMode, pickWeighted } from './lib/modes.js';
                import { prepare, call, replay, lifecycle as walkLifecycle, seed, cleanup, setupAuth, preview as previewRequests, previewJourney as printJourney, previewLifecycle as printLifecycle } from './lib/http.js';
                import { runChannels } from './lib/channels.js';
                import { summary } from './lib/report.js';
                import * as grafana from './lib/grafana.js';
                import * as hooks from './hooks.js';
                %s
                const CONFIG = JSON.parse(open('./loadtest.config.json'));

                // Pools are SharedArrays: loaded once, shared read-only by every VU.
                function sharedPools(prefix, text, pick) {
                  const pools = {};
                  for (const key of Object.keys(pick(JSON.parse(text)) || {})) {
                    pools[key] = new SharedArray(`${prefix}:${key}`, () => pick(JSON.parse(text))[key] || []);
                  }
                  return pools;
                }
                const REAL_TEXT = open('./data/real.json');
                const USER_TEXT = open('./data/user.json');
                data.init({
                  config: CONFIG,
                  dictionaries: JSON.parse(open('./lib/dictionaries.json')),
                  real: sharedPools('real', REAL_TEXT, (d) => d),
                  userFields: sharedPools('user', USER_TEXT, (d) => d.fields),
                  userPayloads: sharedPools('payload', USER_TEXT, (d) => d.payloads),
                });

                // Recorded browser flow (generate --har): replayed by MODE=journey-<profile>.
                const JOURNEY = new SharedArray('journey', () => JSON.parse(open('./data/journey.json')));

                // Business flows generated from the code (create → read → update → status → delete per resource):
                // MODE=lifecycle-<profile>.
                const LIFECYCLE = new SharedArray('lifecycle', () => JSON.parse(open('./data/lifecycle.json')));

                // WebSocket, STOMP and SSE endpoints (MODE=channels-<profile>).
                const CHANNELS = new SharedArray('channels', () => JSON.parse(open('./data/channels.json')));

                // Test data created in setup through the application's create endpoints, parents before children
                // (entity relationships); see README "Seeding".
                const SEED = JSON.parse(open('./data/seed.json'));

                // What a successful response of each API must look like (checked on a sample of responses).
                const RESPONSE_SCHEMAS = JSON.parse(open('./data/response-schemas.json'));

                const MODULES = [
                %s];
                const RUNTIME = prepare(CONFIG, MODULES, SEED, RESPONSE_SCHEMAS);
                export const options = buildOptions(CONFIG, RUNTIME, JOURNEY.length, LIFECYCLE.length, CHANNELS.length);

                export function setup() {
                  if (parseMode(__ENV.MODE).profile === 'preview') return { headers: {}, seeded: {} };
                  const annotation = grafana.start(parseMode(__ENV.MODE).mode, RUNTIME.dataMode, RUNTIME.baseUrl);
                  const auth = setupAuth(CONFIG);
                  auth.seeded = seed(RUNTIME, SEED, auth, hooks);
                  auth.annotation = annotation;
                  return auth;
                }

                export function teardown(data) {
                  cleanup(RUNTIME, SEED, data, hooks);
                  if (data) grafana.end(data.annotation);
                }

                %sexport function mixed(auth) {
                  call(pickWeighted(RUNTIME.apis), RUNTIME, auth, hooks);
                }

                export function all(auth) {
                  for (const api of RUNTIME.apis) call(api, RUNTIME, auth, hooks);
                }

                export function journey(auth) {
                  replay(RUNTIME, JOURNEY, auth, hooks);
                }

                export function lifecycle(auth) {
                  walkLifecycle(RUNTIME, LIFECYCLE, auth, hooks);
                }

                export async function channels(auth) {
                  await runChannels(RUNTIME, CHANNELS, auth);
                }

                export function previewLifecycle() {
                  printLifecycle(RUNTIME, LIFECYCLE, hooks);
                }

                export function preview() {
                  previewRequests(RUNTIME, hooks);
                }

                export function previewJourney() {
                  printJourney(RUNTIME, JOURNEY, hooks);
                }

                export default function (auth) {
                  mixed(auth);
                }

                export function handleSummary(result) {
                  return summary(result, RUNTIME, parseMode(__ENV.MODE).mode);
                }
                """.formatted(String.join(" | ", LoadMode.modeNames()), imports, list, execs);
    }

    static String json(Object value) {
        return Documents.json().writeValueAsString(value);
    }
}
