package com.springaimcpservercommon.loadtest.k6;

import com.springaimcpservercommon.loadtest.data.DataPlan;
import com.springaimcpservercommon.loadtest.data.FieldPlan;
import com.springaimcpservercommon.loadtest.data.LifecyclePlan;
import com.springaimcpservercommon.loadtest.discovery.ResponseSchemas;
import com.springaimcpservercommon.loadtest.data.SeedPlan;
import com.springaimcpservercommon.loadtest.data.UserData;
import com.springaimcpservercommon.loadtest.model.ApiCatalog;
import com.springaimcpservercommon.loadtest.model.ApiEndpoint;
import tools.jackson.databind.JsonNode;

import java.util.List;
import java.util.Map;

/**
 * Renders the generated suite's {@code README.md}: how to run it, the modes, the data modes, and tables of the
 * APIs and of every field with its data provider.
 */
final class SuiteReadme {

    private SuiteReadme() {
    }

    static String render(ApiCatalog catalog, DataPlan plan, Map<String, List<Object>> pools, UserData user,
                         JsonNode config, @org.jspecify.annotations.Nullable SeedPlan seed,
                         @org.jspecify.annotations.Nullable LifecyclePlan lifecycle) {
        StringBuilder md = new StringBuilder();
        md.append("# k6 load tests — ").append(catalog.project()).append("\n\n");
        md.append("Generated by `spring-ai-mcp-server-common-loadtest` from the project's ")
                .append("sources/OpenAPI/actuator mappings. Regenerate after API changes; your edits to ")
                .append("`loadtest.config.json`, `data/user.json` and `hooks.js` are kept.\n\n");
        md.append("Target: `").append(config.path("baseUrl").asString()).append("` (override with `BASE_URL`).\n\n");
        md.append("## Run\n\n```\n");
        md.append("./run.sh smoke                        # every API on its own, a few iterations — run first\n");
        md.append("./run.sh preview random               # print generated requests, send nothing\n");
        md.append("./run.sh mixed-load                   # realistic weighted mix of all APIs\n");
        md.append("./run.sh mixed-spike mixed            # spike, data drawn from every source\n");
        md.append("API=").append(catalog.endpoints().isEmpty() ? "someApi" : catalog.endpoints().getFirst().id())
                .append(" ./run.sh stress dummy   # stress one API with dummy data\n");
        md.append("VUS=50 DURATION_SCALE=0.2 ./run.sh mixed-stress   # bigger, shorter\n");
        md.append("```\n\nOr directly: `k6 run -e MODE=mixed-stress -e DATA_MODE=real main.js`. ")
                .append("Reports land in `reports/` (JSON + Markdown) and a per-API table is printed.\n\n");

        md.append("## Modes (`MODE`)\n\n| Profile | Per-API | Mixed | Recorded journey | What it does |\n"
                + "|---|---|---|---|---|\n");
        for (LoadMode m : LoadMode.values()) {
            md.append("| ").append(m.id()).append(" | `").append(m.id()).append("` | `mixed-").append(m.id())
                    .append("` | `journey-").append(m.id()).append("` | ").append(m.description()).append(" |\n");
        }
        md.append("\nJourney modes replay `data/journey.json` — the API calls of a browser recording (Chrome DevTools ")
                .append("▸ Network ▸ Export HAR, then `generate --har`) in order, with their pauses; ids returned ")
                .append("by one call and sent by a later one are correlated. `./run.sh journey-preview` prints the ")
                .append("steps.\n");
        md.append("\nPer-API modes run each API in its own scenario, one after the other (`PER_API=parallel` to ")
                .append("overlap them; `API=a,b` to pick). Mixed modes run one scenario that picks an API per ")
                .append("iteration by `apis.<id>.weight`. Profiles live in `loadtest.config.json → modes`; scale ")
                .append("with `VUS`, `RATE` and `DURATION_SCALE` without editing.\n\n");

        md.append("## Data modes (`DATA_MODE`)\n\n| Mode | Values come from |\n|---|---|\n");
        md.append("| `auto` (default) | user values, else real values, else dummy values |\n");
        md.append("| `dummy` | realistic generated values per field kind (identifiers stay real) |\n");
        md.append("| `random` | random values within the declared constraints; 4xx counted as expected |\n");
        md.append("| `real` | values sampled from the database / harvested from the API |\n");
        md.append("| `user` | your values from `data/user.json` |\n");
        md.append("| `mixed` | per field and request, weighted by `data.mix` |\n\n");
        md.append("`data/user.json`: `fields` (key → values; key = full field key, `<api|Schema>.<field>` or ")
                .append("bare field name), `payloads` (api id → whole bodies), `bindings` (field key → ")
                .append("`table.column`, applied at the next generation).\n\n");

        md.append("## Realistic traffic: business flows, hot rows, per-VU rows\n\n");
        if (lifecycle == null || lifecycle.flows().isEmpty()) {
            md.append("No resource has a create endpoint plus a read, update, action or delete endpoint, so ")
                    .append("`lifecycle-<profile>` has no flow.\n\n");
        } else {
            md.append("`./run.sh lifecycle-load` walks each resource through its life: create → read → update → ")
                    .append("status transitions → actions → delete, with the id the create returned fed into every ")
                    .append("step (`data/lifecycle.json`, `LIFECYCLE=<name,…>` narrows). Flows found:\n\n");
            for (LifecyclePlan.Flow f : lifecycle.flows()) {
                md.append("- `").append(f.name()).append("`: ").append(f.steps().size()).append(" steps\n");
            }
            md.append("\nDELETE of a row the flow created itself runs even though DELETE is off for shared data ")
                    .append("(`lifecycle.deleteOwnRows`).\n\n");
        }
        md.append("Real values are drawn uniformly by default. `SKEW=zipf` (or `data.skew.mode`) makes a few rows hot ")
                .append("like production traffic (`SKEW=hot` with `hotFraction`/`hotShare`; `SKEW_S` for the Zipf ")
                .append("exponent). `PARTITION=vu` (or `data.partition.mode`) gives every VU its own slice of each ")
                .append("pool for writes, so concurrent updates and deletes do not fight over rows.\n\n");

        md.append("## Production-shaped load\n\n")
                .append("- **Traffic import**: `loadtest traffic --suite . --access-log access.log` (common/combined or ")
                .append("JSON lines) or `--metrics http://app/actuator/prometheus --period 7d` (Micrometer ")
                .append("`http_server_requests`) sets every API's `weight` to its production share (APIs production never ")
                .append("calls get 0), the `production` profile's rate and peak from the observed arrival rate, and keeps ")
                .append("session transitions in `data/traffic.json`. `--apply-slo` also turns observed p95 and server error ")
                .append("rates into thresholds. Run `./run.sh mixed-production` (open model: observed mix and rate) or ")
                .append("`./run.sh session-load` (sessions follow the observed endpoint-to-endpoint transitions).\n")
                .append("- **Open model**: `MODEL=open` (or `model: open`) runs `load`/`stress`/`soak`… as arrival rates ")
                .append("(`RATE` = requests/s at multiplier 1) — users arrive on schedule however slow the service gets; a ")
                .append("`dropped_iterations` threshold fails the run when the generator cannot keep up (`allowDropped` for ")
                .append("stress/spike/breakpoint).\n")
                .append("- **Warm-up**: `load`, `stress`, `soak` and `production` start with a warm-up (`warmup.duration`, ")
                .append("`WARMUP=60s|off`) whose requests are tagged `warmup_<api>` and left out of thresholds and reports, ")
                .append("so JIT compilation, cold caches and empty connection pools do not fail the run.\n\n");

        md.append("## Server-side checks and profiling\n\n")
                .append("`loadtest run` (and `./run.sh`) samples the target's own `/actuator/prometheus` during the run ")
                .append("(`serverChecks.url` to change it, `--no-server-checks` to skip) and fails the run with exit code 4 ")
                .append("when the service itself shows trouble although every request succeeded: threads waiting for ")
                .append("database connections (HikariCP pending in more than 20% of the samples), GC taking more than 5% ")
                .append("of the wall time, any 5xx counted by the server, logged errors. Warnings (not failures): ")
                .append("connection pool, request threads or heap close to their limit, CPU-bound process, leaking threads. ")
                .append("Checks whose metric the service does not expose are skipped; limits live in ")
                .append("`loadtest.config.json → serverChecks`.\n\n")
                .append("`loadtest run --jfr [--jvm-match regex | --jvm-pid n] [--jfr-package com.acme]` records the ")
                .append("target's JVM with Java Flight Recorder (`jcmd`) during the run and analyzes it into the hot-spot ")
                .append("report (CPU, allocation, GC, lock contention) in `reports/`; remote targets: ")
                .append("`scripts/perf-test.sh` or a `--jcmd 'docker exec app jcmd'` prefix.\n\n");

        md.append("## Resilience: faults under load (Toxiproxy)\n\n")
                .append("Real outages are partial and messy — a slow network, a throttled link, connections reset, a ")
                .append("dependency that disappears — and the interesting question is not whether the service errors ")
                .append("*during* the fault but whether it **recovers** after it. [Toxiproxy](https://github.com/Shopify/toxiproxy) ")
                .append("sits between k6 and the application (and between the application and its database or ")
                .append("downstream services); the suite injects its toxics on a schedule while the normal load runs.\n\n")
                .append("```bash\n")
                .append("loadtest resilience-init --suite . [--dependency db=host.docker.internal:5432:15432]\n")
                .append("docker compose -f resilience/docker-compose.yml up -d\n")
                .append("loadtest run --suite . --mode mixed-load --resilience [--experiment outage]\n")
                .append("# or plain k6: k6 run -e MODE=mixed-load -e RESILIENCE=on -e BASE_URL=http://localhost:8666/… main.js\n")
                .append("```\n\n")
                .append("`loadtest.config.json → resilience` lists the proxies and the experiments (`slow-network`, ")
                .append("`narrow-bandwidth`, `connection-resets`, `outage`, plus latency and outage per `--dependency`). ")
                .append("Each starts `startAfter` into the measured run, injects its `toxics` for `duration`, then ")
                .append("`recovery` is watched; `expect` says what is acceptable *during* the fault (`maxErrorRate`, ")
                .append("`p95Ms`) and *after* it (`recoveryMaxErrorRate`, `recoveryP95Ms`; default: the normal ")
                .append("thresholds). Requests are tagged `fault:<name>`, `fault:recover_<name>` or `fault:none`: the ")
                .append("run-wide thresholds count only `fault:none`, so an injected outage does not fail the run, while ")
                .append("a service that stays broken afterwards does (exit 99, named in the report's Resilience table). ")
                .append("Toxiproxy is checked before the run (exit 5 when absent) and reset afterwards; server-side ")
                .append("5xx / log-error checks are relaxed because faults cause them by design. The point of an ")
                .append("experiment is a *timeout, retry, circuit-breaker or fallback* that is configured but never ")
                .append("exercised — a `down` toxic on the database proxy shows whether the pool fails fast and the ")
                .append("service heals.\n\n");

        md.append("## CI: pipeline, baseline gate, pull-request comment, trend\n\n")
                .append("```bash\n")
                .append("loadtest init-ci --provider github|gitlab|jenkins --project .   # writes the pipeline\n")
                .append("```\n\n")
                .append("The pipeline builds and starts the application, runs the suite on every pull request and push ")
                .append("(`smoke`) and nightly (`mixed-load`), and fails when thresholds fail or when an API regressed against ")
                .append("the baseline (`compare`: p95 +20%, errors +1 pp). The baseline (`baseline/<mode>.json`) and the ")
                .append("trend (`history/<mode>.jsonl`) are kept between builds by the CI cache and refreshed by the main ")
                .append("branch; the first run on main becomes the baseline. `loadtest compare --ci` (or `loadtest run ")
                .append("--ci --baseline …`) writes `reports/pr-comment.md` — verdict, per-API comparison, a p95 / req/s / ")
                .append("error trend with a note when the newest p95 sits well above the median of the recent runs ")
                .append("(a slow drift no single comparison flags) — appends it to the job summary (`$GITHUB_STEP_SUMMARY`) ")
                .append("and the GitHub workflow posts it as one comment per pull request, updated in place. ")
                .append("`loadtest trend [--record] [--max-drift 25]` prints the history and can gate on drift. Maven: ")
                .append("`mvn …loadtest-maven-plugin:compare -Dloadtest.ci=true`; Gradle: `loadtestCompare -Ploadtest.ci`.\n\n");

        long uploads = catalog.endpoints().stream().filter(e -> "multipart".equals(e.bodyType())).count();
        long forms = catalog.endpoints().stream().filter(e -> "form".equals(e.bodyType())).count();
        long graphQl = catalog.endpoints().stream().filter(e -> e.isGraphQl()).count();
        md.append("## Beyond JSON over HTTP\n\n")
                .append("- **Uploads and forms**: ").append(uploads).append(" multipart/form-data and ").append(forms)
                .append(" urlencoded endpoints; a file field is sent as a generated file of `data.files.sizeKb` KB ")
                .append("(type from the field name: `avatar` → png, `report` → pdf, `data` → csv).\n")
                .append("- **GraphQL**: ").append(graphQl).append(" operations from the `.graphqls` schema, each a POST ")
                .append("with a generated query document and variables; a 200 with an `errors` member fails the ")
                .append("check; queries are allowed under `READ_ONLY`, mutations named `delete*`/`remove*` are off.\n");
        int channelCount = config.path("channels").size();
        if (channelCount > 0) {
            md.append("- **Channels** (WebSocket, STOMP, SSE, Kafka): `./run.sh channels-smoke` exercises ")
                    .append(channelCount).append(" of them (`data/channels.json`; `loadtest.config.json → channels` ")
                    .append("holds `hold`, `messages`, `intervalMs`, `expectReply`, `message`; `CHANNEL=<id,…>` ")
                    .append("narrows). SSE endpoints are left out of the per-API load because a stream never ends. ")
                    .append("Kafka topics are produced to by `kafka.js`, which needs a k6 built with ")
                    .append("[xk6-kafka](https://github.com/mostafa/xk6-kafka) (`xk6 build --with ")
                    .append("github.com/mostafa/xk6-kafka`) — not run by the standard k6.\n");
        }
        md.append("\n");

        long restricted = catalog.endpoints().stream().filter(e -> e.access() != null).count();
        md.append("## Authentication\n\n")
                .append("`auth.type` is `").append(config.path("auth").path("type").asString("none")).append("` ")
                .append("(detected from the project's Spring Security setup; `none | bearer | basic | apiKey | login | ")
                .append("form | oauth2`). Secrets only come from the environment: `AUTH_USER`/`AUTH_PASSWORD`, ")
                .append("`AUTH_TOKEN`, `API_KEY`, `OAUTH_TOKEN_URL`/`OAUTH_CLIENT_ID`/`OAUTH_CLIENT_SECRET`.\n\n")
                .append("- **Roles**: ").append(restricted).append(" APIs have access rules read from `@PreAuthorize`/")
                .append("`@Secured`/`@RolesAllowed` and the `SecurityFilterChain` matchers. An API that needs a role ")
                .append("is called as that role (`apis.<id>.auth`), a `permitAll` API without credentials (`\"none\"`). ")
                .append("`auth.users.<ROLE>` holds one identity per role (`<ROLE>_USER`/`_PASSWORD`/`_TOKEN`, ")
                .append("`_CLIENT_ID`/`_CLIENT_SECRET` for OAuth2); other APIs use the `AUTH_*` identity.\n")
                .append("- **Per-VU identities**: `${VU}` in a user name (`\"username\": \"load-${VU}\"`) or ")
                .append("`auth.perVu: true` makes every VU log in as itself instead of sharing one token.\n")
                .append("- **Form login** (`auth.type: form`): GET the login page for the CSRF token, POST the form, keep ")
                .append("the session cookie per VU and send `X-XSRF-TOKEN` (cookie) or the scraped token on writes ")
                .append("(`auth.form`).\n")
                .append("- **OAuth2 / Keycloak** (`auth.type: oauth2`): client-credentials (or password) grant against ")
                .append("`auth.oauth2.tokenUrl`; the token is renewed at 90% of `expires_in` (or `auth.refresh.afterSeconds`).\n")
                .append("- A **401** is answered by one new login and a retry (`auth.retryOn401`), so expired or revoked ")
                .append("tokens do not fail the run.\n\n");

        long checked = catalog.endpoints().stream().filter(e -> !ResponseSchemas.isEmpty(e.responseSchema())).count();
        md.append("## Response validation and read-after-write\n\n")
                .append(checked).append(" of ").append(catalog.endpoints().size()).append(" APIs have a known response ")
                .append("shape (`data/response-schemas.json`: from the OpenAPI response, the Java return type or the ")
                .append("recorded responses). A sample of the successful JSON responses (`validation.sample`, default ")
                .append("25%) is checked against it — wrong type, missing required member, value outside an enum — and a ")
                .append("mismatch fails the run (`response_schema_violations` threshold, `validation.maxViolations`). ")
                .append("`VALIDATE_RESPONSES=log` only reports, `off` disables, `VALIDATE_SAMPLE=1` checks everything. ")
                .append("Lifecycle flows also compare each read with the write before it (a lost update shows up as ")
                .append("`status: wrote \"PAID\", read \"NEW\"`; `read_after_write_mismatches` threshold, ")
                .append("`validation.readAfterWrite`). The checks are lenient: extra members, dates, secrets and ")
                .append("members the response does not return are never mismatches.\n\n");

        md.append("## Seeding (test data from the entity relationships)\n\n");
        if (seed == null || seed.steps().isEmpty()) {
            md.append("No create endpoint maps to a known table, so nothing is seeded; ids come from the database, ")
                    .append("the API (`--harvest`) or `data/user.json`.\n\n");
        } else {
            md.append("Before the load starts, `setup()` creates `seed.perTable` rows per table through these create ")
                    .append("endpoints, parents first, and every later payload and path id draws from the created ids ")
                    .append("(then from sampled data). `SEED=false` skips it, `SEED_PER_TABLE=20` scales it, ")
                    .append("`seed.cleanup`/`SEED_CLEANUP=true` deletes the rows afterwards.\n\n")
                    .append("| # | Table | Create API | Needs | Cleanup API |\n|---:|---|---|---|---|\n");
            int i = 1;
            for (SeedPlan.Step st : seed.steps()) {
                md.append("| ").append(i++).append(" | `").append(st.table()).append("` | `").append(st.api())
                        .append("` | ").append(st.dependsOn().isEmpty() ? "—" : "`" + String.join("`, `", st.dependsOn())
                        + "`").append(" | ").append(st.deleteApi() == null ? "—" : "`" + st.deleteApi() + "`")
                        .append(" |\n");
            }
            md.append('\n');
        }
        md.append("## Grafana dashboard\n\n")
                .append("`grafana/` holds a local Prometheus + Grafana stack. k6 streams its metrics to Prometheus ")
                .append("(remote write), Prometheus also scrapes the application's `/actuator/prometheus`, and the ")
                .append("dashboard shows every API (requests/s, p95/p99, failures) next to the application's HTTP, ")
                .append("HikariCP and JVM metrics, with each run marked as an annotation.\n\n```\n")
                .append("docker compose -f grafana/docker-compose.yml up -d   # Prometheus :9090, Grafana :3000\n")
                .append("GRAFANA=1 ./run.sh mixed-load                         # then open http://localhost:3000\n")
                .append("```\n\n")
                .append("The application needs `io.micrometer:micrometer-registry-prometheus` and ")
                .append("`management.endpoints.web.exposure.include=prometheus`; the scrape target is in ")
                .append("`grafana/prometheus.yml`. Pick a run with the *Test run* variable (`testid`). Elsewhere: ")
                .append("`K6_PROMETHEUS_RW_SERVER_URL`, `GRAFANA_URL`, `GRAFANA_TOKEN`. The compose file, ")
                .append("`prometheus.yml` and provisioning are yours after the first generation; ")
                .append("`dashboards/k6-load-test.json` is regenerated (save your changes under another name).\n\n");
        md.append("## APIs\n\n| id | Endpoint | Weight | Enabled | Source |\n|---|---|---:|---|---|\n");
        for (ApiEndpoint e : catalog.endpoints()) {
            JsonNode c = config.path("apis").path(e.id());
            md.append("| `").append(e.id()).append("` | `").append(e.method()).append(' ').append(e.path())
                    .append("` | ").append(c.path("weight").asInt()).append(" | ")
                    .append(c.path("enabled").asBoolean(true) ? "yes" : "no").append(" | ")
                    .append(String.join(", ", e.sources())).append(" |\n");
        }
        md.append("\nDELETE operations are disabled by default (destructive on shared data); enable them per API.\n\n");

        md.append("## Fields and their providers\n\n| Field key | Kind | Real data | User values |\n|---|---|---|---:|\n");
        for (FieldPlan f : plan.fields().values()) {
            String real = f.pool() == null ? (f.sensitive() ? "never (sensitive)" : "—")
                    : "`" + f.pool().key() + "` (" + pools.getOrDefault(f.pool().key(), List.of()).size() + ")";
            md.append("| `").append(f.key()).append("` | ").append(f.kind().generator()).append(" | ").append(real)
                    .append(" | ").append(user.valuesFor(f.key(), f.owner()).size()).append(" |\n");
        }
        md.append("\n## Files\n\n")
                .append("- `apis/<id>.js` — request builder per API; `providers/schemas.js` — data provider per DTO ")
                .append("(generated)\n")
                .append("- `lib/` — runtime (data sources, dummy/random generators, modes, HTTP, report)\n")
                .append("- `hooks.js` — `beforeRequest`/`afterResponse` customisation (yours)\n")
                .append("- `data/real.json`, `data/user.json`, `data/plan.json` — real pools, your values, field plan\n")
                .append("- `grafana/` — Prometheus + Grafana stack and dashboard; `reports/` — one JSON + Markdown ")
                .append("report per run (`loadtest compare` gates regressions)\n");
        return md.toString();
    }
}
