package com.springaimcpservercommon.loadtest.k6;

import com.springaimcpservercommon.loadtest.data.DataPlan;
import com.springaimcpservercommon.loadtest.data.FieldPlan;
import com.springaimcpservercommon.loadtest.data.UserData;
import com.springaimcpservercommon.loadtest.model.ApiCatalog;
import com.springaimcpservercommon.loadtest.model.ApiEndpoint;
import tools.jackson.databind.JsonNode;

import java.util.List;
import java.util.Map;

/**
 * Renders the generated suite's {@code README.md}: how to run it, the modes, the data modes, and tables of the
 * APIs and of every field with its data provider.
 */
final class SuiteReadme {

    private SuiteReadme() {
    }

    static String render(ApiCatalog catalog, DataPlan plan, Map<String, List<Object>> pools, UserData user,
                         JsonNode config) {
        StringBuilder md = new StringBuilder();
        md.append("# k6 load tests — ").append(catalog.project()).append("\n\n");
        md.append("Generated by `spring-ai-mcp-server-common-loadtest` from the project's ")
                .append("sources/OpenAPI/actuator mappings. Regenerate after API changes; your edits to ")
                .append("`loadtest.config.json`, `data/user.json` and `hooks.js` are kept.\n\n");
        md.append("Target: `").append(config.path("baseUrl").asString()).append("` (override with `BASE_URL`).\n\n");
        md.append("## Run\n\n```\n");
        md.append("./run.sh smoke                        # every API on its own, a few iterations — run first\n");
        md.append("./run.sh preview random               # print generated requests, send nothing\n");
        md.append("./run.sh mixed-load                   # realistic weighted mix of all APIs\n");
        md.append("./run.sh mixed-spike mixed            # spike, data drawn from every source\n");
        md.append("API=").append(catalog.endpoints().isEmpty() ? "someApi" : catalog.endpoints().getFirst().id())
                .append(" ./run.sh stress dummy   # stress one API with dummy data\n");
        md.append("VUS=50 DURATION_SCALE=0.2 ./run.sh mixed-stress   # bigger, shorter\n");
        md.append("```\n\nOr directly: `k6 run -e MODE=mixed-stress -e DATA_MODE=real main.js`. ")
                .append("Reports land in `reports/` (JSON + Markdown) and a per-API table is printed.\n\n");

        md.append("## Modes (`MODE`)\n\n| Mode | Per-API form | Mixed form | What it does |\n|---|---|---|---|\n");
        for (LoadMode m : LoadMode.values()) {
            md.append("| ").append(m.id()).append(" | `").append(m.id()).append("` | `mixed-").append(m.id())
                    .append("` | ").append(m.description()).append(" |\n");
        }
        md.append("\nPer-API modes run each API in its own scenario, one after the other (`PER_API=parallel` to ")
                .append("overlap them; `API=a,b` to pick). Mixed modes run one scenario that picks an API per ")
                .append("iteration by `apis.<id>.weight`. Profiles live in `loadtest.config.json → modes`; scale ")
                .append("with `VUS`, `RATE` and `DURATION_SCALE` without editing.\n\n");

        md.append("## Data modes (`DATA_MODE`)\n\n| Mode | Values come from |\n|---|---|\n");
        md.append("| `auto` (default) | user values, else real values, else dummy values |\n");
        md.append("| `dummy` | realistic generated values per field kind (identifiers stay real) |\n");
        md.append("| `random` | random values within the declared constraints; 4xx counted as expected |\n");
        md.append("| `real` | values sampled from the database / harvested from the API |\n");
        md.append("| `user` | your values from `data/user.json` |\n");
        md.append("| `mixed` | per field and request, weighted by `data.mix` |\n\n");
        md.append("`data/user.json`: `fields` (key → values; key = full field key, `<api|Schema>.<field>` or ")
                .append("bare field name), `payloads` (api id → whole bodies), `bindings` (field key → ")
                .append("`table.column`, applied at the next generation).\n\n");

        md.append("## APIs\n\n| id | Endpoint | Weight | Enabled | Source |\n|---|---|---:|---|---|\n");
        for (ApiEndpoint e : catalog.endpoints()) {
            JsonNode c = config.path("apis").path(e.id());
            md.append("| `").append(e.id()).append("` | `").append(e.method()).append(' ').append(e.path())
                    .append("` | ").append(c.path("weight").asInt()).append(" | ")
                    .append(c.path("enabled").asBoolean(true) ? "yes" : "no").append(" | ")
                    .append(String.join(", ", e.sources())).append(" |\n");
        }
        md.append("\nDELETE operations are disabled by default (destructive on shared data); enable them per API.\n\n");

        md.append("## Fields and their providers\n\n| Field key | Kind | Real data | User values |\n|---|---|---|---:|\n");
        for (FieldPlan f : plan.fields().values()) {
            String real = f.pool() == null ? (f.sensitive() ? "never (sensitive)" : "—")
                    : "`" + f.pool().key() + "` (" + pools.getOrDefault(f.pool().key(), List.of()).size() + ")";
            md.append("| `").append(f.key()).append("` | ").append(f.kind().generator()).append(" | ").append(real)
                    .append(" | ").append(user.valuesFor(f.key(), f.owner()).size()).append(" |\n");
        }
        md.append("\n## Files\n\n")
                .append("- `apis/<id>.js` — request builder per API; `providers/schemas.js` — data provider per DTO ")
                .append("(generated)\n")
                .append("- `lib/` — runtime (data sources, dummy/random generators, modes, HTTP, report)\n")
                .append("- `hooks.js` — `beforeRequest`/`afterResponse` customisation (yours)\n")
                .append("- `data/real.json`, `data/user.json`, `data/plan.json` — real pools, your values, field plan\n");
        return md.toString();
    }
}
