# brew bundle --file local-dev/Brewfile
brew "process-compose"
brew "git"
brew "maven"
brew "gradle"
brew "k6"
brew "openjdk@21"
brew "openjdk@17"
cask "orbstack"   # or docker / colima: needed for grafana, loki, prometheus, postgres
