package com.springaimcpservercommon.ruleengine.store;

import com.springaimcpservercommon.core.id.Ids;
import com.springaimcpservercommon.ruleengine.model.ApiEndpoint;
import com.springaimcpservercommon.ruleengine.model.ApiEnvironment;
import com.springaimcpservercommon.ruleengine.model.ChannelType;
import org.jspecify.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * The delivery outbox ({@code dai_re_dispatch}, OQ-67). Rows are claimed with {@code FOR UPDATE SKIP LOCKED} and a
 * time-limited lease, so any number of nodes can drain the queue without double-claiming and a node that dies mid-send
 * only delays its rows until the lease expires. Delivery is at-least-once; the dispatch id travels with API calls so
 * receivers can de-duplicate. Recipients are scrubbed from a row as soon as it is delivered.
 */
public final class OutboxStore {

    /** A row as shown to operators; the payload (personal data) is not included. */
    public record DeadLetter(UUID id, ChannelType channelType, int attempts, @Nullable String lastError,
                             Instant createdAt, Instant updatedAt) {
    }

    private final JdbcRunner jdbc;

    /**
     * Creates the store.
     *
     * @param dataSource data source (not closed)
     * @param schema     schema holding the tables
     */
    public OutboxStore(DataSource dataSource, String schema) {
        this.jdbc = new JdbcRunner(dataSource, schema);
    }

    /**
     * Queues one communication.
     *
     * @param id            dispatch id (generated by the caller so it can be put in the payload)
     * @param tenantId      tenant
     * @param channelType   channel
     * @param bindingId     the channel binding that asked for it, or {@code null}
     * @param apiEndpointId API: endpoint
     * @param payloadJson   JSON to send
     * @param maxAttempts   attempts before the row is dead (1..50)
     */
    public void enqueue(UUID id, UUID tenantId, ChannelType channelType, @Nullable UUID bindingId,
                        @Nullable UUID apiEndpointId, String payloadJson, int maxAttempts) {
        jdbc.write(c -> JdbcRunner.update(c,
                "INSERT INTO dai_re_dispatch (id, tenant_id, channel_type, binding_id, api_endpoint_id, payload, max_attempts)"
                        + " VALUES (?, ?, ?, ?, ?, ?::jsonb, ?)",
                id, tenantId, channelType.name(), bindingId, apiEndpointId, payloadJson, maxAttempts));
    }

    /**
     * Claims up to {@code batch} due rows for {@code lease}: due = PENDING with {@code next_attempt_at <= now()}, and
     * either unlocked or with an expired lease. The claim increments {@code attempts}, so a worker that crashes
     * after sending still counts the attempt. Every time comparison uses the <b>database</b> clock, which all nodes
     * share, so clock skew between application nodes cannot make a row early, late or double-claimed.
     *
     * @param workerId id of the claiming worker (recorded for diagnosis)
     * @param batch    most rows
     * @param lease    how long the rows stay claimed
     * @return the claimed rows
     */
    public List<OutboxItem> claim(String workerId, int batch, java.time.Duration lease) {
        return jdbc.write(c -> JdbcRunner.query(c,
                "UPDATE dai_re_dispatch d SET attempts = d.attempts + 1, locked_until = now() + make_interval(secs => ?),"
                        + " locked_by = ?"
                        + " WHERE d.id IN (SELECT id FROM dai_re_dispatch WHERE status = 'PENDING' AND next_attempt_at <= now()"
                        + " AND (locked_until IS NULL OR locked_until <= now()) ORDER BY next_attempt_at LIMIT ? FOR UPDATE SKIP LOCKED)"
                        + " RETURNING d.id, d.tenant_id, d.channel_type, d.api_endpoint_id, d.payload::text, d.attempts,"
                        + " d.max_attempts, d.created_at",
                rs -> new OutboxItem(rs.getObject(1, UUID.class), rs.getObject(2, UUID.class),
                        ChannelType.valueOf(rs.getString(3)), rs.getObject(4, UUID.class), rs.getString(5),
                        rs.getInt(6), rs.getInt(7), rs.getTimestamp(8).toInstant()),
                lease.toMillis() / 1000.0, workerId, batch));
    }

    /**
     * Marks a row delivered and scrubs its payload (the recipient is personal data).
     *
     * @param id dispatch id
     */
    public void delivered(UUID id) {
        jdbc.write(c -> JdbcRunner.update(c,
                "UPDATE dai_re_dispatch SET status = 'DELIVERED', delivered_at = now(), payload = '{}'::jsonb,"
                        + " locked_until = NULL, locked_by = NULL, last_error = NULL WHERE id = ?", id));
    }

    /**
     * Records a failed attempt: the row goes back to PENDING for {@code nextAttemptAt}, or is dead when no attempt is
     * left or the failure cannot be retried.
     *
     * @param id      dispatch id
     * @param error   short error code (never a message that could carry personal data)
     * @param retryIn how long from now until the next attempt
     * @param dead    {@code true} to stop retrying now
     */
    public void failed(UUID id, String error, java.time.Duration retryIn, boolean dead) {
        jdbc.write(c -> JdbcRunner.update(c,
                "UPDATE dai_re_dispatch SET status = CASE WHEN ? OR attempts >= max_attempts THEN 'DEAD' ELSE 'PENDING' END,"
                        + " next_attempt_at = now() + make_interval(secs => ?), last_error = ?, locked_until = NULL,"
                        + " locked_by = NULL WHERE id = ?",
                dead, retryIn.toMillis() / 1000.0, error, id));
    }

    /**
     * Deletes delivered rows older than {@code deliveredAge} and dead rows older than {@code deadAge}.
     *
     * @param deliveredAge age of DELIVERED rows to delete
     * @param deadAge      age of DEAD rows to delete
     * @return rows deleted
     */
    public int purge(java.time.Duration deliveredAge, java.time.Duration deadAge) {
        return jdbc.write(c -> JdbcRunner.update(c,
                "DELETE FROM dai_re_dispatch WHERE (status = 'DELIVERED' AND updated_at < now() - make_interval(secs => ?))"
                        + " OR (status = 'DEAD' AND updated_at < now() - make_interval(secs => ?))",
                deliveredAge.toMillis() / 1000.0, deadAge.toMillis() / 1000.0));
    }

    /**
     * Dead rows of a tenant, newest first.
     *
     * @param tenantId tenant
     * @param limit    most rows (1..500)
     * @return dead letters without payload
     */
    public List<DeadLetter> deadLetters(UUID tenantId, int limit) {
        return jdbc.read(c -> JdbcRunner.query(c,
                "SELECT id, channel_type, attempts, last_error, created_at, updated_at FROM dai_re_dispatch"
                        + " WHERE tenant_id = ? AND status = 'DEAD' ORDER BY updated_at DESC LIMIT ?",
                rs -> new DeadLetter(rs.getObject(1, UUID.class), ChannelType.valueOf(rs.getString(2)), rs.getInt(3),
                        rs.getString(4), rs.getTimestamp(5).toInstant(), rs.getTimestamp(6).toInstant()),
                tenantId, Math.min(Math.max(limit, 1), 500)));
    }

    /**
     * Gives a dead row one more round of attempts (operator action).
     *
     * @param tenantId tenant (a row of another tenant is never touched)
     * @param id       dispatch id
     * @return {@code true} if a dead row was re-queued
     */
    public boolean retry(UUID tenantId, UUID id) {
        return jdbc.write(c -> JdbcRunner.update(c,
                "UPDATE dai_re_dispatch SET status = 'PENDING', attempts = 0, next_attempt_at = now(), last_error = NULL"
                        + " WHERE id = ? AND tenant_id = ? AND status = 'DEAD'", id, tenantId)) == 1;
    }

    /**
     * Counts rows by status (health and tests).
     *
     * @param status PENDING, DELIVERED or DEAD
     * @return rows in that status
     */
    public long count(String status) {
        return jdbc.read(c -> JdbcRunner.queryOne(c, "SELECT count(*) FROM dai_re_dispatch WHERE status = ?",
                rs -> rs.getLong(1), status));
    }

    /**
     * Loads an endpoint for sending (the environment guard runs on the current row, not on a copy made at queue time).
     *
     * @param id endpoint id
     * @return the endpoint, or {@code null} if it no longer exists or is inactive
     */
    public @Nullable ApiEndpoint endpoint(UUID id) {
        return jdbc.read(c -> JdbcRunner.queryOne(c,
                "SELECT id, name, http_method, url, environment, timeout_ms, auth_secret_ref, external_confirmed_by,"
                        + " external_confirmed_at FROM dai_re_api_endpoint WHERE id = ? AND active",
                rs -> {
                    Timestamp confirmedAt = rs.getTimestamp(9);
                    return new ApiEndpoint(rs.getObject(1, UUID.class), rs.getString(2), rs.getString(3),
                            rs.getString(4), ApiEnvironment.valueOf(rs.getString(5)), rs.getInt(6), rs.getString(7),
                            rs.getString(8), confirmedAt == null ? null : confirmedAt.toInstant());
                }, id));
    }

    /**
     * A fresh dispatch id.
     *
     * @return UUIDv7
     */
    public static UUID newId() {
        return Ids.newId();
    }
}
